# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot = {
    kernelPackages = pkgs.linuxPackages_xanmod_latest;
    initrd = {
      kernelModules = [ ];
      availableKernelModules =
      [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    kernelParams = [ ];
  };
  # enable proper mouse usage on xorg.
  services.xserver.libinput.enable = true;
  hardware = {
    # needed from monitor resolution
    video.hidpi.enable = true;
    # needed for some games
    opengl = {
      enable = true;
      driSupport = true;
    };
    # laptop supports bt
    bluetooth.enable = true;
  };
  disko.devices = import ../../modules/disko/lvm-luks.nix {
    disks = [ "/dev/sda" ];
    # partitionSizes = [ "34G" "40%" "55%" ];
  };
  # dynamic dhcp
  # networking.useDHCP = true;
  # SSD optimization
  fileSystems."/".options = [ "noatime" "nodiratime" "discard" ];
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;
  powerManagement.cpuFreqGovernor = "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
