# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];
  boot = {
    #    kernelPackages = pkgs.linuxPackages_xanmod_latest;
    initrd = {
      kernelModules = ["dm-snapshot" "vendor-reset"];
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "uas"
        "usb_storage"
        "usbhid"
        "sd_mod"
        "amdgpu"
        "vendor-reset"
      ];
    };
    kernelModules = [
      "kvm-intel"
      "amdgpu"
      "vendor-reset"
    ];
    supportedFilesystems = ["ntfs"];
    extraModulePackages = with config.boot.kernelPackages; [vendor-reset];
    kernelParams = [];
    kernelPatches = [
      {
        name = "config";
        patch = null;
        extraConfig = ''
          KALLSYMS_ALL y
          FTRACE y
          KPROBES y
          PCI_QUIRKS y
          KALLSYMS y
          FUNCTION_TRACER y
        '';
      }
    ];
  };
  services.xserver.videoDriver = "i915";

  fileSystems."/run/media/sky/windows10" = {
    device = "/dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S59ANMFNB34577E-part3";
    fsType = "auto";
    options = ["nosuid" "nodev" "nofail" "x-gvfs-show"];
  };
  # enable proper mouse usage on xorg.
  services.xserver.libinput.enable = true;
  hardware = {
    # needed from monitor resolution
    #video.hidpi.enable = true;
    # needed for some games
    opengl = {
      enable = true;
      driSupport = true;
    };
    # laptop supports bt
    bluetooth.enable = true;
  };
  boot.initrd.luks.devices.crypted.device = "/dev/disk/by-id/usb-_USB_DISK_3.2_0700199604A32D02-0:0-part3";
  disko.devices = import ../../modules/disko/lvm-luks.nix {
    disks = ["/dev/disk/by-id/usb-_USB_DISK_3.2_0700199604A32D02-0:0"];
    partitionSizes = ["34G" "120G" "700G"];
  };
  # dynamic dhcp
  networking.useDHCP = lib.mkDefault true;
  # SSD optimization
  fileSystems."/".options = ["noatime" "nodiratime" "discard"];
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;
  powerManagement.cpuFreqGovernor = "powersave";
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
