{ config, lib, pkgs, ... }:

{
  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=2
      DEVPATH=hwmon4=devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0
      DEVNAME=hwmon4=amdgpu
      FCTEMPS=hwmon4/pwm1=hwmon4/temp1_input
      FCFANS=hwmon4/pwm1=hwmon4/fan1_input
      MINTEMP=hwmon4/pwm1=30
      MAXTEMP=hwmon4/pwm1=70
      MINSTART=hwmon4/pwm1=200
      MINSTOP=hwmon4/pwm1=0
      MAXPWM=hwmon4/pwm1=255

    '';
  };
}
